title: My Minimalistic Portfolio
description: A clean and minimalistic website for my articles
baseurl: ""
url: "https://DanSop.github.io"
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  articles:
    output: true
    permalink: /articles/:path/
