title: My Minimalistic Portfolio
description: A clean and minimalistic website for my articles
baseurl: ""
url: "https://username.github.io"
markdown: kramdown
kramdown:
  math_engine: mathjax
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
