title: "My Minimalistic Portfolio"
description: "A clean and minimalistic website for my articles."
#baseurl: "" 
url: "https://DanSop.github.io"
theme: null  
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

