title: DanSop's Blog
description: A minimalist blog supporting markdown, LaTeX, code, and media
url: "" 
baseurl: ""

markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

paginate: 5
paginate_path: "/page/:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:title/"

plugins:
  - jekyll-paginate
  - jekyll-feed
